language: node_js
node_js:
  - "stable"
dist: trusty
cache:
 directories:
   - "node_modules"
services:
  - postgresql
  - apt-get install postgresql-11
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
host: localhost
env:
  global:
    - export NODE-ENV=test
    - PGPORT=5432
before_script:
 - npm install
 - npm run build
 - psql -c 'create database questionaire_api_test;' -U postgres
 - npm run createTable
script:
 - npm test
after_success:
 - npm run coverage 