language: node_js
node_js:
  - "stable"
dist: trusty
cache:
 directories:
   - "node_modules"
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
host: localhost
env:
  global:
    - export NODE-ENV=test
    - PGPORT=5433
before_script:
 - npm install
 - npm run build
 - psql -c 'create database questionaire_api_test;' -U postgres
 - npm run createTable
script:
 - npm test
after_success:
 - npm run coverage 