language: node_js
node_js:
  - "stable"
env:
global:
  - export NODE_ENV=test
dist: trusty
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql
notifications:
  email: true
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database questionaire_api_test;' -U postgres
  - npm install
script: 
  - npm test
after_success:
  - npm run coverage