language: node_js
node_js:
  - "stable"
before_install:
  - psql -c "psql -U postgres"
  - psql -c "ALTER USER postgres WITH PASSWORD 'tolumide';" -U postgres
cache:
 directories:
   - "node_modules"
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
host: localhost
env:
  global:
    - export NODE-ENV=test
before_script:
 - npm install
 - npm run build
 - psql -c 'CREATE DATABASE questionaire_api_test;' -U postgres
 - psql -c "ALTER USER postgres WITH PASSWORD 'tolumide';" -U postgres
script:
 - npm test
after_success:
 - npm run coverage 